
## 异常

### 01 异常的概念以及抛出异常的原因


```python
#提示用户输入一个整数
num = int(input("输入整数"))
```

    输入整数10
    


```python
num = int(input("输入整数"))
```

    输入整数a
    


    --------------------------------------------------------------------------

    ValueError                               Traceback (most recent call last)

    <ipython-input-4-ba4a30183a12> in <module>()
    ----> 1 num = int(input("输入整数"))
    

    ValueError: invalid literal for int() with base 10: 'a'


### 02 简单的异常捕获

```python 
try:
    尝试执行的代码
except:
    出现错误的处理
```


```python
try:
    num = int(input("请输入一个整数"))
except:
    print("请输入正确的整数")

```

    请输入一个整数a
    请输入正确的整数
    

### 03 根据错误类型捕获异常

在程序执行时，可能会遇到不同类型的异常，并且需要针对不同类型的异常，  
做出不同的响应.  

```python
try:
    #尝试执行的代码
    pass
except 错误类型1:
    #针对错误类型1，对应的代码处理
except (错误类型2,错误类型3):
    #针对错误类型2，3,对应的代码处理

``` 


```python
try:
    num = int(input("请输入一个整数"))
    result = 8 / num
    print(result)
except ZeroDivisionError:
    print("除0错误")
except ValueError:
    print("请输入正确的整数")
```

    请输入一个整数a
    请输入正确的整数
    

### 04 捕获未知错误

```python
except Exception as result(变量名):
    print("未知错误: %s" % result(变量名))
```


```python
try:
    num = int(input("请输入一个整数"))
    result = 8 / num
    print(result)
except ValueError:
    print("请输入正确的整数")
except Exception as result:
    print("未知错误:%s" % result)
```

    请输入一个整数0
    未知错误:division by zero
    

### 05 异常捕获完整语法

```python 
try:
    #尝试执行的代码
    pass
except 错误类型1:
    #针对错误类型1，对应的代码处理
except (错误类型2,错误类型3):
    #针对错误类型2，3,对应的代码处理
except Exception as result:
    #打印错误
    print(result)
else:
    #没有异常才会执行的代码
    pass
finally:
    #无论是否有异常，都会被执行
    print("无论是否有异常，都会被执行")
``` 


```python
try:
    num = int(input("请输入一个整数"))
    result = 8 / num
    print(result)
except ValueError:
    print("请输入正确的整数")
except Exception as result:
    print("未知错误:%s" % result)
else:
    print("打印成功")
finally:
    print("finally")
```

    请输入一个整数3
    2.6666666666666665
    打印成功
    finally
    

### 06 异常的传递性


```python
def demo1():
    return int(input("输入整数："))

print(demo1())
```

    输入整数：a
    


    --------------------------------------------------------------------------

    ValueError                               Traceback (most recent call last)

    <ipython-input-24-7b3a7abe28b5> in <module>()
          2     return int(input("输入整数："))
          3 
    ----> 4 print(demo1())
    

    <ipython-input-24-7b3a7abe28b5> in demo1()
          1 def demo1():
    ----> 2     return int(input("输入整数："))
          3 
          4 print(demo1())
    

    ValueError: invalid literal for int() with base 10: 'a'



```python
def demo1():
    return int(input("输入整数："))

def demo2():
    return demo1()

print(demo2())
```

    输入整数：a
    


    --------------------------------------------------------------------------

    ValueError                               Traceback (most recent call last)

    <ipython-input-26-329be530e1ff> in <module>()
          5     return demo1()
          6 
    ----> 7 print(demo2())
    

    <ipython-input-26-329be530e1ff> in demo2()
          3 
          4 def demo2():
    ----> 5     return demo1()
          6 
          7 print(demo2())
    

    <ipython-input-26-329be530e1ff> in demo1()
          1 def demo1():
    ----> 2     return int(input("输入整数："))
          3 
          4 def demo2():
          5     return demo1()
    

    ValueError: invalid literal for int() with base 10: 'a'



```python
def demo1():
    return int(input("输入整数："))

def demo2():
    return demo1()
#利用异常的传递性，在主程序中捕获异常
try:
    print(demo2())
except Exception as result:
    print("%s" % result)
```

    输入整数：a
    invalid literal for int() with base 10: 'a'
    

### 07 主动抛出异常

抛出异常
* 创建一个`Exception`的对象
* 使用`raise`关键字抛出异常对象


```python
def input_password():
    #1.提示输入密码
    pwd = input("请输入密码:")
    #2.判断密码长度 >=8
    if len(pwd) >= 8:
        return pwd
    #3.如果 < 8 主动抛出异常
    #3.1 创建Exception -> 可以使用错误信息字符串作为参数
    ex = Exception("密码长度不够")
    #3.2主动抛出异常
    raise ex
    
#提示用户输入密码
try:
    print(input_password())
except Exception as result:
    print(result)
```

    请输入密码:321
    密码长度不够
    

